plugins {
    id 'base'
}

allprojects {
    group = findProperty('mod_group_id') ?: 'com.alanjmrt94.consolefilternext'
}

tasks.named('build').configure {
    dependsOn ':common:build', ':forge:build'
}

tasks.register('testAll') {
    group = 'verification'
    description = 'Ejecuta tests de common y forge'
    dependsOn ':common:test', ':forge:test'
}
