# Pins de Minecraft 1.12.2 (Forge legacy). Núcleo Java 8 en common-java8 + legacy-common.
minecraft_version=1.12.2
mod_version=1.12.2-4.2.0
java_version=8
forge_version=14.23.5.2860
mcp_mapping_channel=stable
mcp_mapping_version=39
