# Pins de Minecraft 1.19.4 (Forge + Fabric). Sin NeoForge. Sin editor in-game.
minecraft_version=1.19.4
mod_version=1.19.4-4.2.0
java_version=17

# Forge
forge_version=45.4.5
forge_version_range=[45,)
loader_version_range=[45,)
minecraft_version_range=[1.19.4,1.20)

# Fabric
loom_version=1.14.1
fabric_loader_version=0.16.14
fabric_api_version=0.87.2+1.19.4
