# Pins de Minecraft 1.8.9 (Forge legacy). Núcleo Java 8 en common-java8 + legacy-common.
minecraft_version=1.8.9
mod_version=1.8.9-4.2.0
java_version=8
forge_version=11.15.1.2318-1.8.9
mcp_mappings=stable_20
